# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59509821e84a145a9bbfe85e281809ea448c60bc06ab1f01454bd496c3f3dee103049e322866a901584d7af5fcabb3bc1d5a4a295f3085ba3ca926e4c4bb7763
  uclassify_api_key: <%= ENV["UCLASSIFY_KEY"] %>
test:
  secret_key_base: fa4ed88b29f6183ee42039410f6f3caa308daba422dec74b9befd4c1b5d1bb02652fc1ef9c313237007f2deed536178e00a90243a7a711f6130e6c059061747e
  uclassify_api_key: <%= ENV["UCLASSIFY_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  uclassify_api_key: <%= ENV["UCLASSIFY_KEY"] %>
